#!/bin/sh
# Sets colors from pywal to cava dynamically 
# The name for the cava color file can be anything really, I just used this to go along with my other templates.
# Do note, that if you want to change any configuration in cava, you WILL have to do it through the configuration file in the TEMPLATES FOLDER.
cp ~/.cache/wal/colors-cava.conf ~/.config/cava/config

pkill -USR2 cava # Reloads cava's colorscheme configuration
